### ISSUE TITLE
Problems in the description of cards

### ISSUE THREAD

**Issue by RaiderYavin** [eBaeza/aoe3de-deck-builder#1]
Problemas en la descripción de cierto envío en el deck de los lakota.
![image](https://user-images.githubusercontent.com/102546932/160457419-61a3e628-0367-4e10-a9ad-e3aafb039516.png)

**Comment by eBaeza** [comment]
Closing this issue, since it is the same text from the game, probably a game bug, but i'm not updating any sources. I hope they fixed in a next release and i could update the sources.
