### ISSUE TITLE
Support Chinese

### ISSUE THREAD

**Issue by JpyChiu** [eBaeza/aoe3de-deck-builder#4]
Hi @eBaeza 
I want to introduce this app on the Chinese forum.
So I made a dropdown menu for language choosing.

But I have no idea about aoe3 game files, idk where to find these translated text files.
Would you teach me how to do it?

My discord: `啾以#6509`

![aoe3-deck-lang](https://user-images.githubusercontent.com/40068919/163973426-5769fb93-9aaa-4527-aef3-61233e8f085e.gif)

**Comment by eBaeza** [comment]
Added support to chinese language
